/**
 * The Worker's secrets, declared by hand.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` and knows only
 * what `wrangler.jsonc` declares — bindings and vars. Secrets are set out of
 * band (`wrangler secret put …`) and deliberately appear in no committed file,
 * so nothing generates a type for them, and without one `env.GOOGLE_API_KEY`
 * is a compile error.
 *
 * Declaring them here rather than adding them to `wrangler.jsonc` as `vars`
 * keeps that true: a `vars` entry would be a real, plaintext, committed
 * variable that *overrides* the secret of the same name, which is the one way
 * to turn a secret into a non-secret without noticing. TypeScript merges
 * interface declarations, so this augments the generated `Env` rather than
 * replacing it.
 *
 * Set them with, from this directory:
 *
 *     npx wrangler secret put GOOGLE_CALENDAR_ID
 *     npx wrangler secret put GOOGLE_API_KEY
 */
interface Env {
  /** The public calendar's id, as Google Calendar's "Integrate calendar" gives it. */
  GOOGLE_CALENDAR_ID: string;
  /** A Google Cloud API key with the Calendar API enabled. */
  GOOGLE_API_KEY: string;
}
