/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 05c7afbc5d0b1190078144fe70e3c519)
interface __BaseEnv_Env {
	BOX_PRICES: KVNamespace;
	CALENDAR: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
