/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 120e991c673e1861dfcefed595137d5a)
interface __BaseEnv_Env {
	BOX_PRICES: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
